### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Techwolf12** [erwinhenraat/littleRocketApp#1]
Beste Erwin,

Ik heb wat feedback voor je op je git gebruik:
- In de root directory zet je verschillende (binary?) versies van je applicatie. Een git repository is niet bedoeld voor binary bestanden maar voor source code. Een handige manier van toch versies bijhouden is het [taggen van een punt in de source code](https://git-scm.com/book/en/v2/Git-Basics-Tagging).
- De gitignore file is niet op de juiste manier geschreven, ook bestaan er [templates](https://github.com/github/gitignore/blob/master/Actionscript.gitignore) voor projecten die, bijvoorbeeld in dit geval, met actionscript zijn gemaakt. Een gitignore moet ook altijd toegevoegd zijn voordat je de bestanden die je in de repo wil gooien commit.
- Git repositories zouden altijd een README.md bestand moeten hebben waar informatie over het project in staat. Dit bestand schrijf je in markdown (net zoals [dit bericht](http://ix.io/NcG)!)

En nog een stukje feedback op je [code](https://github.com/erwinhenraat/littleRocketApp/blob/e5d6391cec8d8290e6797d069293af19f06f30e7/src/Plane.as#L138), waar de manier van mijn schrijven een stuk overzichtelijker zal zijn en er netter uit ziet.  
Jou manier:  

``` Actionscript
public function shoot():void 
{
    //schieten
    for (var i:int = 0; i < main.wingmen.length; i++) 
    {
        main.wingmen[i].shoot();
    }
```

Mijn manier:  

``` Actionscript
/*
* Documentatie over wat deze functie doet
* Kan op meerdere regels, deze functie schiet bijvoorbeeld
*/
public function shoot():void {
    for (var i:int = 0; i < main.wingmen.length; i++) {
        // Inline code documentatie over een bepaald object
        main.wingmen[i].shoot();
    }
```

Hopelijk heb je hier iets aan!  

Christiaan

**Comment by erwinhenraat** [comment]
Bedankt voor je feedback deze is zeker welkom.
